### ISSUE TITLE
I get this error while I try to run the SUEWS Simple model_ I prepared Meteorological Data using MetPreprocessor with out any error

### ISSUE THREAD

**Issue by shahjahan0275** [UMEP-dev/UMEP#198] opened 2020-11-07 16:16 UTC
```
2020-11-07T22:00:52     WARNING    Traceback (most recent call last):
              File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SuewsSimple\suews_simple.py", line 594, in start_progress
              suews_wrapper.wrapper(self.model_dir, year=YYYY)
              File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\suews_wrapper.py", line 51, in wrapper
              df_forcing = sp.load_forcing_grid(path_runcontrol, grid).loc[f'{year}'] # new (loc) from 2020a
              File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\supy\_supy_module.py", line 205, in load_forcing_grid
              path_input, filecode, grid, tstep_met_in, multiplemetfiles
              File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\supy\_load.py", line 657, in load_SUEWS_Forcing_met_df_raw
              path_input, forcingfile_met_pattern
              File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\supy\_load.py", line 709, in load_SUEWS_Forcing_met_df_pattern
              df_forcing_met.columns = col_suews_met_forcing
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\generic.py", line 5287, in __setattr__
              return object.__setattr__(self, name, value)
              File "pandas\_libs\properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\generic.py", line 661, in _set_axis
              self._data.set_axis(axis, labels)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\internals\managers.py", line 178, in set_axis
              f"Length mismatch: Expected axis has {old_len} elements, new "
             ValueError: Length mismatch: Expected axis has 38 elements, new values have 24 elements
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SuewsSimple\suews_simple.py", line 598, in start_progress
              "Check also: " + str(list(Path.cwd().glob('SuPy.log'))[0]) + "\r\n\r\n"
             IndexError: list index out of range
```

**Comment by Empanag** [comment] 2020-11-07 16:18
Can you upload the txt with meteorological data?

**Comment by shahjahan0275** [comment] 2020-11-07 19:21
[ctg1.txt](https://github.com/UMEP-dev/UMEP/files/5505324/ctg1.txt)
Attached is the file with meteorological data. Thanks

**Comment by shahjahan0275** [comment] 2020-11-07 19:47
I used six variables U, RH, Tair, pres, rain and Kdown which are minimum requirement to run SUEWS. But I couldn't figure out why this error occurring. So I am stuck. Any help will be greatly appreciated. Regards

**Comment by Empanag** [comment] 2020-11-08 03:27
You have to use metdata processor. This seems to be modified, the variables has different name etc and I think some of them are missing. You can see the test data for example.

**Comment by shahjahan0275** [comment] 2020-11-08 12:08
I used metdata processor. But now I am getting the following error even with the test data file:
```
ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Check also: C:\Users\Lenovo\OneDrive\Documents\supy.log

Please report any errors to https://github.com/UMEP-dev/UMEP/issues

```

**Comment by sunt05** [comment] 2020-11-09 17:01
Sorry to learn the issue but it's unclear to me what the issue is.

Can you please answer the following questions:
1. can you report the following version info?
in you QGIS python console, do the following:
```
import supy as sp
sp.show_version()

```
please report the output here.


2. are you still using the [test forcing file](https://github.com/UMEP-dev/UMEP/files/5505324/ctg1.txt) uploaded above?

This file should be OK with SUEWS/SuPy: I just tested it.

3. > I used metdata processor. But now I am getting the following error even with the test data file:

what is this "test data file" you are referring to? can you upload it?

**Comment by DimitrisTsi** [comment] 2021-04-08 05:27
Hello everyone. I am facing the same issue as shahjahan0275 while trying to run suews simple.
What i have done so far is this:
 - firstly i ran suews simple using the 'add settings from test dataset' option to check that everything is ok, and indeed the program runs smoothly with no errors and the expected results.
 - then i change the meteorological file with mine , and also change the 'year' to '2020' as this is the year the meteorological data corresponds to. Below is my meteorological data file
[herv2__met_proc_2020_data_60.txt](https://github.com/UMEP-dev/UMEP/files/6276224/herv2__met_proc_2020_data_60.txt)
After pressing 'run', i get the following error :
```
Length mismatch: Expected axis has 38 elements, new values have 24 elements

Check also: C:\Users\RSLab1720\Documents\supy.log

Please report any errors to https://github.com/UMEP-dev/UMEP/issues
```
- The weird thing about this is situation is that, when i try to run suews simple again (after the error occurs) using the test dataset from the 'add settings from test dataset' option, the same error occurs!

My supy and relevant dependencies info : 
```
SuPy versions
-------------
supy: 2021.1.7 
supy_driver: 2020b10

=================
SYSTEM DEPENDENCY

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.1.3
numexpr          : 2.7.2
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.16.2
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : None
numba            : 0.52.0
```
Thanks in advance

**Comment by biglimp** [comment] 2021-04-08 07:55
I cannot reproduce your error exactly but I cannot run the model with your metdatafile. @sunt05, I get the error below just replacing the metfile using the Sample dataset.

Please inform us on the following:

1. Where are your metdatafile from? It seems that it is not for a location near London, UK? If not, you need to adjust the lat and lon and maybe other parameters.
2. @sunt05 , The metfile used is including leapday. Can this be an issue? Also, the last timestep is not included (2021 1 0 0 ...). Could that be an issue?

![image](https://user-images.githubusercontent.com/11908356/113989193-7e60a280-9850-11eb-87bf-e483498171ce.png)

**Comment by DimitrisTsi** [comment] 2021-04-08 08:05
The metdatfile is from Heraklion, Greece, however i get the same error when using the correct parameters. Also, i have tested using only the first 24 lines of the metdat file as input (to check a smaller timeframe) but still the same error occurs
![Στιγμιότυπο 2021-04-05, 10 51 09 πμ](https://user-images.githubusercontent.com/20373671/113990546-3e9eb880-985a-11eb-8f70-9a02739030d8.png)
Thanks

**Comment by sunt05** [comment] 2021-04-08 08:46
Hi @DimitrisTsi,

your [met file](https://github.com/UMEP-dev/UMEP/files/6276224/herv2__met_proc_2020_data_60.txt) seems to be OK and I can successfully run supy outside of the UMEP env.

Hi @biglimp,
also I can use `save_supy` to export all results without any issue: [supy-output.zip](https://github.com/UMEP-dev/UMEP/files/6277337/supy-output.zip).
I guess there might some other files in the UMEP input folder that confuse UMEP/SuPy to pick up the correct ones. Maybe you can tell @DimitrisTsi what files/folders should be zipped and posted here for our further debugging.

**Comment by biglimp** [comment] 2021-04-08 11:59
@DimitrisTsi , locate the **suewsmodel** directory which should be located here is you are a windows user: C:\Users\**your_username**\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\suewsmodel\Input. I recommend that you delete the content and re-run SuewsSimple to get rid of any unnecessary files. Then zip the input folder and attach it here.

**Comment by DimitrisTsi** [comment] 2021-04-08 14:35
here is the input folder content @biglimp 
[Input.zip](https://github.com/UMEP-dev/UMEP/files/6279420/Input.zip)

**Comment by biglimp** [comment] 2021-04-14 14:03
@sunt05 , can you test these input files. It produce error in SUEWSSimple for me.

[Input.zip](https://github.com/UMEP-dev/UMEP/files/6311326/Input.zip)


![image](https://user-images.githubusercontent.com/11908356/114723473-f809fc00-9d3a-11eb-8924-05823f086e22.png)

**Comment by sunt05** [comment] 2021-04-14 14:07
@biglimp thanks for the archive: I'll test it later today.

**Comment by sunt05** [comment] 2021-04-14 22:29
@biglimp I tried your input files and nothing went wrong here. we may discuss this tomorrow (i.e., Thur.).

**Comment by biglimp** [comment] 2021-04-15 07:57
There is something very strange here. I tried to run in QGIS Python Console and that worked. Output files are written to disk. Any idea what is happening (based on the error above). Unfortunately, I am in a meeting all day today.

`import supy as sp`
`from pathlib import Path`
`path_runcontrol = Path(r'C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\suewsmodel\RunControl.nml')`
`df_state_init = sp.init_supy(path_runcontrol)`
`grid = df_state_init.index[0]`
`df_forcing = sp.load_forcing_grid(path_runcontrol, grid)`
`df_output, df_state_final = sp.run_supy(df_forcing, df_state_init)`
`list_path_save = sp.save_supy(df_output, df_state_final, path_runcontrol=path_runcontrol)`

**Comment by sunt05** [comment] 2021-04-15 08:03
sorry I couldn't figure out the issue based on the error above.
we may need to write some debugging code inside UMEP to dump `df_forcing`, `df_state_init`, `df_output` and `df_state_final` to understand what's actually happening there.

**Comment by biglimp** [comment] 2021-04-15 08:12
What code should I add?

**Comment by sunt05** [comment] 2021-04-15 08:17
> What code should I add?

in the `suews_wrapper` code, add something like the following:
```
import supy as sp
from pathlib import Path
path_runcontrol = Path(r'C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\suewsmodel\RunControl.nml')
df_state_init = sp.init_supy(path_runcontrol)
p_debug_save= path_runcontrol.parent
# start dumping useful df's
df_state_init.to_pickle(p_debug_save/'df_state_init.pkl')
grid = df_state_init.index[0]
df_forcing = sp.load_forcing_grid(path_runcontrol, grid)
df_forcing.to_pickle(p_debug_save/'df_forcing.pkl')


df_output, df_state_final = sp.run_supy(df_forcing, df_state_init)
df_output.to_pickle(p_debug_save/'df_output.pkl')
df_state_final.to_pickle(p_debug_save/'df_state_final.pkl')
list_path_save = sp.save_supy(df_output, df_state_final, path_runcontrol=path_runcontrol)

``` 

then after running suews in UMEP, we should get some `pkl` files in your `C:\Users\xlinfr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\suewsmodel`.

please post those here as a zip and I'll take them for debugging.

**Comment by biglimp** [comment] 2021-04-15 13:42
Finally I found the issue. The first line in the metdata from @DimitrisTsi is not correct (2020 0 0 1 ...). This does not exist for 2020 as this is the last hour of 2019. Remove first line and try again.

**Comment by DimitrisTsi** [comment] 2021-04-15 15:54
@biglimp indeed that was the issue, suews simple runs smoothly after removing the first line. 
Thanks a lot!

**Comment by sunt05** [comment] 2021-04-15 18:08
> Finally I found the issue. The first line in the metdata from @DimitrisTsi is not correct (2020 0 0 1 ...). This does not exist for 2020 as this is the last hour of 2019. Remove first line and try again.

I think you meant `2020 1 0 0 ...`? since that's what I see in @DimitrisTsi 's [met file](https://github.com/UMEP-dev/UMEP/files/6276224/herv2__met_proc_2020_data_60.txt)
But that's a valid timestamp representation.
So now it's me who really get confused...

**Comment by biglimp** [comment] 2021-04-16 06:13
Yes, @sunt05 you are correct. I will close this issue now and put in a warning about errors in the metfile.

**Closed as completed by biglimp** 2021-04-16 06:13 UTC

**Comment by shahjahan0275** [comment] 2021-07-03 18:29
@biglimp, sorry that I have to comment again on this closed issue. I am uploading met data of my hometown Chittagong, Bangladesh. I think this met file doesn't have the line you mentioned in  @DimitrisTsi 's met file. Still it gives me error once I run SUEWS with this met file. Strange thing is that once I tried to run SUEWS with my met file, after that I can't run even the SUEWS simple using the 'add settings from test dataset' option.
[ctg_2016.txt](https://github.com/UMEP-dev/UMEP/files/6758873/ctg_2016.txt)
![Error](https://user-images.githubusercontent.com/39149359/124363736-d136d400-dc5e-11eb-9ad1-dfe1491427b1.jpg)

**Comment by shahjahan0275** [comment] 2021-07-03 18:31
I am using QGIS 3.16 and python 3.9. Regards
