### ISSUE TITLE
SUEWS simple model - odd results in output radiation balance about the values of net all wave radiation

### ISSUE THREAD

**Issue by Maurizio112** [UMEP-dev/UMEP#210] opened 2020-12-31 19:05 UTC
Dear developers

I’m using SUEWS simple model in Qgis3.14 to simulate an urban area located in Catania, a Sicilian city along the Mediterranean coast in Italy. I have installed UMEP from zip file named “UMEP-SuPy-QGis3.zip” on 26 June 2020. 
 
 I am facing issues when trying using my own weather file.

In fact, when running the simulations with the settings from my case study (morphology, land cover, etc.) and using my weather file (attached to this email and formatted as per the example one from London), I got the odd results shown in the figure attached. In particular, the output values of incoming short wave radiation (Kdown) are well lower than values that I provided as input in Meteorological file. In addition, the hourly trend of Kdown is flat during all the year.

To be sure the issue was in the weather file, I run simulations with the settings from my case study (morphology, land cover, etc.) and the London weather file provided as example. In such a case, I got reasonable results indeed.

The weather file of Catania, attached to this email along with the example London one, includes the must-use (MU) input variables (U, RH, Tair, press, rain, Kdown) related to the investigated area. I have opened Kc_2011_data_60.txt (i.e. the example one for London) and file meteoCatania.txt in Notepad++. Each column of meteorological variables was copied from meteoCatania.txt and pasted in Kc_2011_data_60.txt keeping the original format.

Best regards
![Odd results weather file Catania](https://user-images.githubusercontent.com/76165290/103422725-25270a00-4ba3-11eb-999a-1c3df69ac08b.jpg)
[Kc_2011_data_60.txt](https://github.com/UMEP-dev/UMEP/files/5758089/Kc_2011_data_60.txt)

**Comment by sunt05** [comment] 2021-01-06 22:08
I need more input from you to help you out:
1. Please follow this to locate the UMEP installation folder on your machine:
https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location
2. Run UMEP-SUEWS-Simple with your problematic forcing file;
3. In the folder located in step 1, there is folder named “suewsmodel”, zip it and upload the zip archive here.

Thanks!

**Comment by sunt05** [comment] 2021-01-08 16:22
@Maurizio112 per our email correspondence, I consider this issue can be marked as resolved.

The issue is actually due to incorrect file naming that doesn't comply with SUEWS file convention; @biglimp but we may need to check why there's no issue being triggered.

**Comment by biglimp** [comment] 2021-01-11 12:58
Ok, I keep this in mind.

**Closed as completed by biglimp** 2021-01-11 12:58 UTC
