### ISSUE TITLE
UMEP vegetation porosity

### ISSUE THREAD

**Issue by ghost** [UMEP-dev/UMEP#215] opened 2021-01-08 11:30 UTC
I don't have data about the vegetation porosity for the UMEP-Input. I only have informations about the LAI, VegetationType, patch and vegetation on buildings. Is it possible to generate the Footprint anyway?

**Comment by biglimp** [comment] 2021-01-08 13:27
Yes. Use default values if you dont have etter information. This is not a bug. I will close this. Please use email list for general questions.

**Closed as completed by biglimp** 2021-01-08 13:27 UTC

**Comment by suegrimmond** [comment] 2021-01-11 13:12
you can use literature values that vary with season (the most important part)
