### ISSUE TITLE
SOLWEIG Analyzer outputs raster with Nodata values

### ISSUE THREAD

**Issue by j0lsson** [UMEP-dev/UMEP#217] opened 2021-01-14 16:15 UTC
Hi! 

When I try to calculate "Percent of time above threshold" the resulting raster contains rows with Nodata value.. It seems that when all pixels in a row are below the threshold the result is Nodata instead of 0. Calculating daytime average etc works fine. Is it a bug or can it be related to my input data? I use QGIS 3.16.2 and UMEP 3.15.5.

![image](https://user-images.githubusercontent.com/77452966/104616931-2a985000-568b-11eb-93f6-c7cac02b3490.png)

Best regards!

**Comment by sunt05** [comment] 2021-01-14 18:05
duplicate of #218

**Closed as completed by sunt05** 2021-01-14 18:05 UTC
