### ISSUE TITLE
UMEP Pre-Processor cutting off decimal places

### ISSUE THREAD

**Issue by oliver-michels** [UMEP-dev/UMEP#194] opened 2020-11-02 16:13 UTC
Dear all

I use the UMEP Pre-Processor --> "Prepare existing data" to format my dataframes, in this case a .csv file I created in Python, to the correct format to read in to SuPy. 

Whenever I do this though, it cuts off two to three places after the decimal point, like in this case for Wind(Speed), please note in the screenshots it is 0.0001 until its being processed in the Pre-Processor and comes out as 0.0.   Are there any ideas to what is causing this problem? 

Kind regards

![dataframe in python](https://user-images.githubusercontent.com/63778850/97462708-4d924e00-193f-11eb-97e4-5b100fc7f26e.png)
![CSV file before formatting](https://user-images.githubusercontent.com/63778850/97462724-5125d500-193f-11eb-9f2e-a0a332717d99.png)
![processed to text file](https://user-images.githubusercontent.com/63778850/97462739-5420c580-193f-11eb-9c54-bef25f746efd.png)

**Comment by biglimp** [comment] 2020-11-03 13:14
This is hard coded into the tool since we thought that two significant decimals are enough. If you like to change this you can alter line 715-716 in /UMEP/MetDataProcessor/metdata_processor.py

**Comment by suegrimmond** [comment] 2020-11-03 14:17
2 sig fig - is low for WS

**Comment by biglimp** [comment] 2020-11-03 15:06
Even two sig. decimals. Are you sure?

**Comment by suegrimmond** [comment] 2020-11-03 15:18
can't have 0 WS

**Comment by biglimp** [comment] 2020-11-03 15:50
That is already tested for. WS = 0.01 is the lowest but we can change to more sig numbers

**Comment by suegrimmond** [comment] 2020-11-03 16:16
I think the problem is that there are lower values for 0 @oliver-michels

**Comment by oliver-michels** [comment] 2020-11-03 16:21
That’s correct, the data I‘m working with has 0.0001 as the lowest values for windspeed. 

Thank you for your reply, I will try and fix it at my end.

**Comment by biglimp** [comment] 2020-11-04 10:13
Ok, I will change the sig. numbers for wind speed in upcoming versions. I will close this now. You can use this code below to replace line 715 and 716 in /UMEP/MetDataProcessor/metdata_processor.py

```
        numformat = '%d %d %d %d %.2f %.2f %.2f %.2f %.2f %.5f %.2f %.2f %.2f %.2f %.2f %.2f %.2f ' \
                    '%.2f %.2f %.2f %.2f %.2f %.2f %.2f' 
```

**Closed as completed by biglimp** 2020-11-04 10:13 UTC
